### PR TITLE
Add wireframes refinement 12-06-2019

### PR DESCRIPTION
**Pull request by maxvisser**

### CODE REVIEW

**Comment by jamalv** [comment]
awesome, I also added a wireframes branch, maybe it's better to put them in there?

https://github.com/teamforus/forus/tree/feature/wireframes

**Comment by maxvisser** [comment]
you don't like a specific wireframes folder?

**Comment by jamalv** [comment]
sure, a wireframes folder is good as well 👍 

mostly pointing out there was already a branch, and that were taking two different routes ;)

**Comment by maxvisser** [comment]
ah yes. I will merge this one into that one

**Pull request closed without merging**
